name: Build

on:
  push:
    branches:
      - main
    tags-ignore:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 23
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Store artifacts
        uses: actions/upload-artifact@v4
        with:
          name: lfe-problem-admin
          path: dist/lfe-problem-admin.user.js

  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    permissions:
      contents: write

    steps:
      - name: Generate changelog
        run: pnpm dlx changelogen@latest --output dist/changelog.md

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: dist/changelog.md
          files: dist/lfe-problem-admin.user.js
          token: ${{ secrets.GITHUB_TOKEN }}
